# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20161107_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='exec_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_notification',
            field=models.CharField(choices=[('NOR', 'Не повторять'), ('DAY', 'Ежедневно'), ('WEK', 'Еженедельно'), ('MON', 'Ежемесячно'), ('YER', 'Ежегодно')], default='NOR', max_length=3),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_task',
            field=models.CharField(choices=[('NOR', 'Не повторять'), ('DAY', 'Ежедневно'), ('WEK', 'Еженедельно'), ('MON', 'Ежемесячно'), ('YER', 'Ежегодно')], default='NOR', max_length=3),
        ),
        migrations.AddField(
            model_name='task',
            name='sort_position',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('WRK', 'В работе'), ('WIT', 'Ожидание'), ('DON', 'Завершено'), ('CLD', 'Отменено')], default='NEW', max_length=3),
        ),
    ]
