# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 07:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0004_auto_20161107_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='exec_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='planned_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='repeat_notification',
        ),
        migrations.RemoveField(
            model_name='task',
            name='repeat_task',
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
