# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0009_auto_20161107_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratdf_from', to=settings.AUTH_USER_MODEL, verbose_name='perfjjjormer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to=settings.AUTH_USER_MODEL, verbose_name='authohjr'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='task.tag'),
        ),
    ]
