# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0011_auto_20161107_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notification_task_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='read_permission',
            field=models.ManyToManyField(blank=True, null=True, related_name='read_permission', to=settings.AUTH_USER_MODEL, verbose_name='read_permission'),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_task_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='write_permission',
            field=models.ManyToManyField(blank=True, null=True, related_name='write_permission', to=settings.AUTH_USER_MODEL, verbose_name='write_permission'),
        ),
    ]
