# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 12:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20161107_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='read_permission',
            field=models.ManyToManyField(blank=True, related_name='read_permission', to=settings.AUTH_USER_MODEL, verbose_name='read_permission'),
        ),
        migrations.AlterField(
            model_name='task',
            name='write_permission',
            field=models.ManyToManyField(blank=True, related_name='write_permission', to=settings.AUTH_USER_MODEL, verbose_name='write_permission'),
        ),
        migrations.AddField(
            model_name='task',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.icon'),
        ),
    ]
